//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class applications
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public applications()
        {
            this.application_status_history = new HashSet<application_status_history>();
        }
    
        public long id { get; set; }
        public long job_id { get; set; }
        public long candidate_id { get; set; }
        public long cv_id { get; set; }
        public string cover_letter { get; set; }
        public string status { get; set; }
        public Nullable<decimal> match_score { get; set; }
        public Nullable<byte> required_matched { get; set; }
        public Nullable<byte> required_total { get; set; }
        public string recruiter_note { get; set; }
        public System.DateTime applied_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<application_status_history> application_status_history { get; set; }
        public virtual candidates candidates { get; set; }
        public virtual cvs cvs { get; set; }
        public virtual jobs jobs { get; set; }
    }
}
