//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate_skills
    {
        public long candidate_id { get; set; }
        public int skill_id { get; set; }
        public byte proficiency { get; set; }
        public decimal years_experience { get; set; }
    
        public virtual candidates candidates { get; set; }
        public virtual skills skills { get; set; }
    }
}
