//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class companies
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public companies()
        {
            this.company_members = new HashSet<company_members>();
            this.jobs = new HashSet<jobs>();
        }
    
        public long id { get; set; }
        public string name { get; set; }
        public string tax_code { get; set; }
        public string logo_url { get; set; }
        public string website { get; set; }
        public string industry { get; set; }
        public string company_size { get; set; }
        public string address { get; set; }
        public string city { get; set; }
        public string description { get; set; }
        public bool is_verified { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<company_members> company_members { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<jobs> jobs { get; set; }
    }
}
