//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class company_members
    {
        public long company_id { get; set; }
        public long user_id { get; set; }
        public string full_name { get; set; }
        public string phone { get; set; }
        public string position { get; set; }
        public string member_role { get; set; }
    
        public virtual companies companies { get; set; }
        public virtual users users { get; set; }
    }
}
