//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class cvs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cvs()
        {
            this.applications = new HashSet<applications>();
        }
    
        public long id { get; set; }
        public long candidate_id { get; set; }
        public string title { get; set; }
        public string file_url { get; set; }
        public string parsed_text { get; set; }
        public bool is_default { get; set; }
        public System.DateTime uploaded_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<applications> applications { get; set; }
        public virtual candidates candidates { get; set; }
    }
}
