//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobs
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public jobs()
        {
            this.applications = new HashSet<applications>();
            this.job_skills = new HashSet<job_skills>();
            this.saved_jobs = new HashSet<saved_jobs>();
        }
    
        public long id { get; set; }
        public long company_id { get; set; }
        public long posted_by { get; set; }
        public Nullable<int> category_id { get; set; }
        public string title { get; set; }
        public string slug { get; set; }
        public string description { get; set; }
        public string requirements { get; set; }
        public string benefits { get; set; }
        public string employment_type { get; set; }
        public string level { get; set; }
        public string work_mode { get; set; }
        public string city { get; set; }
        public string address { get; set; }
        public Nullable<int> salary_min { get; set; }
        public Nullable<int> salary_max { get; set; }
        public bool salary_negotiable { get; set; }
        public string currency { get; set; }
        public decimal min_experience_years { get; set; }
        public string min_education { get; set; }
        public short headcount { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> published_at { get; set; }
        public Nullable<System.DateTime> expires_at { get; set; }
        public int view_count { get; set; }
        public System.DateTime created_at { get; set; }
        public System.DateTime updated_at { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<applications> applications { get; set; }
        public virtual companies companies { get; set; }
        public virtual job_categories job_categories { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<job_skills> job_skills { get; set; }
        public virtual users users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<saved_jobs> saved_jobs { get; set; }
    }
}
