//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class application_status_history
    {
        public long id { get; set; }
        public long application_id { get; set; }
        public string from_status { get; set; }
        public string to_status { get; set; }
        public Nullable<long> changed_by { get; set; }
        public string note { get; set; }
        public System.DateTime changed_at { get; set; }
    
        public virtual applications applications { get; set; }
        public virtual users users { get; set; }
    }
}
