//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate_educations
    {
        public long id { get; set; }
        public long candidate_id { get; set; }
        public string school_name { get; set; }
        public string major { get; set; }
        public string degree { get; set; }
        public Nullable<short> start_year { get; set; }
        public Nullable<short> end_year { get; set; }
    
        public virtual candidates candidates { get; set; }
    }
}
