//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class candidate_experiences
    {
        public long id { get; set; }
        public long candidate_id { get; set; }
        public string company_name { get; set; }
        public string job_title { get; set; }
        public System.DateTime start_date { get; set; }
        public Nullable<System.DateTime> end_date { get; set; }
        public string description { get; set; }
    
        public virtual candidates candidates { get; set; }
    }
}
