//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class job_skills
    {
        public long job_id { get; set; }
        public int skill_id { get; set; }
        public string importance { get; set; }
        public byte weight { get; set; }
        public byte min_proficiency { get; set; }
        public decimal min_years { get; set; }
    
        public virtual jobs jobs { get; set; }
        public virtual skills skills { get; set; }
    }
}
