//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class recruitment_dbEntities : DbContext
    {
        public recruitment_dbEntities()
            : base("name=recruitment_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<application_status_history> application_status_history { get; set; }
        public virtual DbSet<applications> applications { get; set; }
        public virtual DbSet<candidate_educations> candidate_educations { get; set; }
        public virtual DbSet<candidate_experiences> candidate_experiences { get; set; }
        public virtual DbSet<candidate_skills> candidate_skills { get; set; }
        public virtual DbSet<candidates> candidates { get; set; }
        public virtual DbSet<companies> companies { get; set; }
        public virtual DbSet<company_members> company_members { get; set; }
        public virtual DbSet<cvs> cvs { get; set; }
        public virtual DbSet<job_categories> job_categories { get; set; }
        public virtual DbSet<job_skills> job_skills { get; set; }
        public virtual DbSet<jobs> jobs { get; set; }
        public virtual DbSet<saved_jobs> saved_jobs { get; set; }
        public virtual DbSet<skill_aliases> skill_aliases { get; set; }
        public virtual DbSet<skill_categories> skill_categories { get; set; }
        public virtual DbSet<skills> skills { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<users> users { get; set; }
    }
}
