//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace recruitment_website.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class saved_jobs
    {
        public long candidate_id { get; set; }
        public long job_id { get; set; }
        public System.DateTime saved_at { get; set; }
    
        public virtual candidates candidates { get; set; }
        public virtual jobs jobs { get; set; }
    }
}
